version: 2

sources:
  - name: raw
    tables:
      - name: customers
      - name: geolocation
      - name: order_items
      - name: order_payments
      - name: order_review
      - name: orders
      - name: product_category_name_translation
      - name: products
      - name: sellers